### ISSUE TITLE
Replicate MAtmos Water/Swimming Sounds

### ISSUE THREAD

**Issue by jimcarreer** [Ambiotic/Ambiotic#13]

**Comment by jimcarreer** [comment]
https://github.com/Ambiotic/Ambiotic/commit/400004819154ebd7f9bd25736ffa8ee770dc5675
Adds underwater loop.

**Comment by crunkazcanbe** [comment]
I would like this feature to .

**Comment by jimcarreer** [comment]
Just doing the underwater loop for now.
