### ISSUE TITLE
Using 0.0.4 - Block Scanner Crash

### ISSUE THREAD

**Issue by crunkazcanbe** [Ambiotic/Ambiotic#18]
I am getting a crash with a mod that adds GUIs to the main MC menu After clicking a button continue to main menu it crashes the game its a mod called modpacktweaks . Crash log here http://pastebin.com/UfGPw6CK BTW using version 0.0.4 of this mod .

**Comment by jimcarreer** [comment]
Is this before our after you join a game / map?

**Comment by crunkazcanbe** [comment]
This is way before man . This is right after mc loads its a new screen you have to click something before you see the main menu .

**Comment by jimcarreer** [comment]
If you're willing to be a test subject, can you try [this jar](https://www.dropbox.com/s/39oldbtozdcw89f/ambiotic-0.0.4.jar?dl=0) I know it says 0.0.4 but it has a prelim change I think will help.

**Comment by crunkazcanbe** [comment]
I just tried it man and unfortunately this version now crashes before it even get to the main menu . Crash log here http://pastebin.com/CfmAcBv5

**Comment by jimcarreer** [comment]
Oh, that's definitely a build error, seems to pop up in the version of forge gradle I'm using from time to time, sorry about that.
Try [this one.](https://www.dropbox.com/s/fr4123rgblxp877/rebuild-ambiotic-0.0.4.jar?dl=0)

**Comment by crunkazcanbe** [comment]
This did not work either crash log here http://pastebin.com/ph1Ma8EZ I believe this happens with 0.0.5 to ,but let me re check this .

**Comment by jimcarreer** [comment]
Might also try [0.0.6](https://github.com/Ambiotic/Ambiotic/releases/tag/0.0.6)

**Comment by jimcarreer** [comment]
I'm pretty sure this is fixed now.
