### ISSUE TITLE
Enhancement Please . I beg of you to add LocalWeather & Storms support .

### ISSUE THREAD

**Issue by crunkazcanbe** [Ambiotic/Ambiotic#19]
As the title says I always had a big dream of MAtmos supporting that mod ,but it never came true . I see the new guy maintaining MAtmos might add support for the Better rain mod now here http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2134067-better-rain-v0-15-bug-fixes but not the weather mod . If you could will you please man I beg add support for the weather mod here http://coros.us/mods/weather2 . This mod adds tornadoes ,and wind hurricanes and such if you don't know about it you should try it . I was wanting you to add wind sounds ,and better tornado sounds and such . This mod supporting the wind in that mod will be very awesome man. Please if you can add support and sounds for that mod ,and also the better rain mod if you can. I will be happy to test the versions of the mod that support it and things for you man,. Thank you very much & I hope you can do this . :)

-Crunk

**Comment by jimcarreer** [comment]
So the problem with integration with these mods is I need some kind of API on their end to integrate with. Without that it'd be really difficult to include variables based on their weather events.  I imagine that's the similar problem that the MAtmos maintainer would have had.

**Comment by jimcarreer** [comment]
I looked for some kind of API for this but I can't find anything really useful.  So I will later base rain / weather related sounds on the rain intensity variable. If this mod updates / acts on that variable there should be some level of compatibility but without an API to interact with I'm not going to "hack" in support for this.
