### ISSUE TITLE
Bug: Sounds pile up and all play at once after leaving pause menu.

### ISSUE THREAD

**Issue by ghost** [Ambiotic/Ambiotic#21]
If you're in an area that that triggers sounds, and you pause, the mod will keep preparing new sounds to play, and when you leave the pause menu, they'll all play at once (not that 1,000 crickets chirping at the same time is unrealistic, but I imagine it's not the intent).

**Comment by jimcarreer** [comment]
Yeah that's a bug.

**Comment by jimcarreer** [comment]
This should be fixed in [0.0.6](https://github.com/Ambiotic/Ambiotic/releases/tag/0.0.6)
