### ISSUE TITLE
O/k I dont mean to nag but..

### ISSUE THREAD

**Issue by crunkazcanbe** [Ambiotic/Ambiotic#22]
Is there anyway you could go back to the old way ,and just include all the resources in your mod ? I love making mod packs ,but now my players will have to go to resource packs to activate this . I would love just to throw it in the mods folder ,and it work . This is one of the reasons I liked this better then MAtmos . I hope I don't come off as annoying man . I promise I don't mean to nag it just that was one of the reasons I liked this over MAtmos .

**Comment by jimcarreer** [comment]
It makes it really hard for me to replace the the vanilla Minecraft sounds that way.  Maybe if I can figure out a way to do that without using a resource pack but there are not a lot of good options for this.

**Comment by jimcarreer** [comment]
I'm not going to do this, but I will open an issue to alert the user that they might need a resource pack and link them to it.

**Comment by jimcarreer** [comment]
You no longer need the resource pack.
