### ISSUE TITLE
Crickets follow you into the sky

### ISSUE THREAD

**Issue by ghost** [Ambiotic/Ambiotic#30]
Cricket sounds continue despite being far away from any grass blocks.

**Comment by jimcarreer** [comment]
Are you using 1.0.0? I do need to detect when the player is "flying" and fix that.

**Comment by ghost** [comment]
Sorry for not specifying. Yes, I am using 1.0.0.

**Comment by jimcarreer** [comment]
Fixed in 1.2.0
