### ISSUE TITLE
Beach sounds while not at the beach v1.2.0

### ISSUE THREAD

**Issue by ghost** [Ambiotic/Ambiotic#31]
After teleporting from a mountain village to a savanna/plains, I get the sound of seagulls and waves. There are no beach biome chunks loaded but the sounds persist. Other sounds (such as birds in trees) will start if I get to the right place for them to do so, but I am haunted by seagulls and a beach I cannot see wherever I go.

Not sure if any of the above is related, but thought I should include it all just in case.

**Comment by jimcarreer** [comment]
Do you have any other mods installed?

**Comment by ghost** [comment]
Quite a few, yes. Does Ambiotic support biomes from the Alternate Terrain Generation mod?

**Comment by jimcarreer** [comment]
Well, those mods may not use BiomeTags properly.  For example Ocean and Beach tags should ONLY be used when your near the ocean, but I know that Enhanced BIomes for instance will tag land biomes with Ocean/Beach tags.

**Comment by ghost** [comment]
Ah okay, thanks for the info, I'll pass that on to the ATG dev.

**Comment by jimcarreer** [comment]
As a work around you can modify emitters/water.json and emitters/beach.json and put them into a custom resource pack to over ride the defaults that I set.  For example you could check LS.Water > 100 as an additional requirement for gull sounds.  I try to make the engine I include by default work with Vanilla Minecraft the best.  I may need to start creating alternative engine resource packs for specific biome mods, but it's a lot of work.

**Comment by ghost** [comment]
Sorry to reopen this, but here's the response I got on the ATG thread; http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291067-atg-alternate-terrain-generation?comment=1912

Neither of the biomes mentioned in the reply to have the beach biome tag were present at the time of the problem.

**Comment by jimcarreer** [comment]
I'm going to need more information then.  Give me a day or two to work up a way for you to dump out the engine variables to a file so I can better examine whats going on.

Also, out of curiosity, did this only occur after a teleport?

**Comment by ghost** [comment]
I've tested it out further and yes, the problem occurs only after teleportation, not while transitioning between biomes on foot or while flying. No matter what biome I teleport to, or from, the beach/ocean sounds persist.

Upon leaving the world and reentering it, the soundscape is appropriate to the location, but teleporting to anywhere on the surface will cause the beach to return.

I've also tested teleporting underground and back up, and this does not cause the beach to appear. However, as soon as I teleport from the surface to another location on the surface, the beach returns. Teleporting underground after that seems to hide the beach, but returning to the surface via teleport returns me to the beach soundscape even when no beach is present.

**Comment by jimcarreer** [comment]
Ah, excellent, then from the sound of this it should occur in Vanilla as well.  Good find! I think I know exactly what causes it!

**Comment by jimcarreer** [comment]
Fixed in https://github.com/Ambiotic/Ambiotic/commit/754aece3166b3cab7f25e6834c33c50cd9fab9da . Thanks for your help with this @Tetrajak, watch for the fix probably in 1.2.2
